первый коммит. Написал функции активации + mse + layer. Завтра нормальное сообщение наберу
boboxa2010/NeuralNetworksFromScratch pull request #1
Opened 2024-01-17 20:34 UTC by boboxa2010

2024-02-05 15:08 UTC, DimaTrushin requested changes
Обрати внимание, что я делал комментарии только в одном месте. Если ошибка повторялась несколько раз, то я не повторялся и ожидаю, что ты по аналогии поправишь во всех аналогичных местах.

В целом выглядит очень неплохо. Видно, что пытался применять замечания из курса по плюсам. Есть несколько странных или сомнительных мест, но я все откомментировал.

2024-02-05 15:08 UTC, DimaTrushin commented on main.cpp
> +    nn::mnist::Data train =
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "NeuralNetwork.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-02-05 15:08 UTC, DimaTrushin commented on main.cpp
> +    nn::AsciiRender(train.X[0], train.y[0]);
Это что еще за хрень?

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.h
> +    ActivationFunction(const FuncT &function, const FuncT &derivative);
Плохо сделано. Ты редко в конструктор подставляешь lvalue объекты, а с таким конструктором нет возможности украсть кишки у rvalue. Я бы либо добавил
```cpp
ActivationFunction(Funct&& function, FuncT&& derivative);
```
Либо сделал шаблонный конструктор
```cpp
template<class F1, class F2>
ActivationFunction(F1&& function, F2&& derivative);
```

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.h
> +
Слишком много вертикальных пробелов. Убрать!

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.h
> +        std::for_each(first, last, [this](Scalar &x) { x = function_(x); });
Не зови напрямую std::function, лучше зови ApplyFunction (какое дурацкое название), потому что внутри ApplyFunction можно поставить assert, что ActivationFunction не пуст.

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.cpp
> +    return function_(x);
добавсь assert(function_); перед вызовом, а то у тебя есть дефолтный конструктор и есть мув операции.

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.cpp
> +                         [](Scalar x) { return exp(x) / ((1 + exp(x)) * (1 + exp(x))); }) {
У тебя выражение может взорваться. Когда ты делишь очень большое, на очень большое, или очень маленькое на очень маленькое. В этом случае exp(x) на exp(x). Перепиши формулу так, чтобы все экспоненты были в знаменателе.

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.cpp
> +                         [](Scalar x) { return x > 0 ? 1 : 0; }) {
Можно упростить
```cpp
return x > 0;
```
Аналогично в первом случае
```cpp
return x * (x > 0);
```

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.cpp
> +    : ActivationFunction([](Scalar x) { return x; }, [](Scalar x) { return 1; }) {
Убери во второй лямбде имя переменной, чтобы не ругался компилятор на неиспользуемый аргумент.

2024-02-05 15:08 UTC, DimaTrushin commented on ActivationFunction.h
> +    ActivationFunction() = default;
Если объект может быть в пустом состоянии после мува или после дефолтного конструктора, то добавь оператор
```cpp
operator bool() const;
```
для проверки, что объект валиден.

2024-02-05 15:08 UTC, DimaTrushin commented on LearningRate.h
интересно

2024-02-05 15:08 UTC, DimaTrushin commented on LossFunctions.h
> +using LossFunction = Any<details::ILossFunction, details::ImplLossFunction>;
Как альтернатива, можно было как и с функцией активации просто хранить две std::function и внутри класса LossFunction.

2024-02-05 15:08 UTC, DimaTrushin commented on LossFunctions.h
> +    MSE() = default;
Не нужно. Дефолтный конструктор и так создастся, если нет никаких других. Убрать.

2024-02-05 15:08 UTC, DimaTrushin commented on LossFunctions.h
> +    Scalar operator()(const Vector &x, const Vector &y) const noexcept;
Если ты стал помечать noexcept методы в этом классе, то стоит пройтись по всем классам и везде, где ты не кидаешь исключения добавить это ключевое слово.

2024-02-05 15:08 UTC, DimaTrushin commented on LossFunctions.cpp
> +    return target - predicted;
Почему тут разность? Ты когда логарифм дифференцируешь, то у тебя отношение должно возникнуть.

2024-02-05 15:08 UTC, DimaTrushin commented on Any.h
> +        return *this;
А почему не дефолтная имплементация вида?
```cpp
return *this = Any(rhs);
```

2024-02-05 15:08 UTC, DimaTrushin commented on Any.h
> +                                          std::is_copy_constructible_v<std::decay_t<T>>>>
1) Так писать плохо. Во-первых, надо заменить это говно на что-то более читаемое с помощью создание constexpr констант с нормальными именами, чтобы было
```cpp
template<typename T, typename = EnableIfNotAny>
```
2) Тебе нет необходимости это писать. Если есть шаблонный конструктор и не шаблонный, то нешаблонный всегда в приоритете. Потому тут можно не выделываться.
3) Судя по твоему условию, ты не понимаешь, что такое universal reference. Когда пишется шаблон
```cpp
template<class T>
Any(T&& value);
```
То T&& это НЕ rvalue reference. Такое выражение биндится и на rvalue и на lvalue reference. Это супер контринтуитивно. Но так устроены плюсы. Потому Scott Meyers называет это универсальной ссылкой.

2024-02-05 15:08 UTC, DimaTrushin commented on Any.h
> +    ~Any() = default;
Можно не писать.

2024-02-05 15:08 UTC, DimaTrushin commented on Any.h
> +        Any(std::forward<std::decay_t<T>>(std::forward<T>(value))).Swap(*this);
1) А зачем тут std::decay_t?
2) Какая хитрая конструкция.

2024-02-05 15:08 UTC, DimaTrushin commented on Any.h
> +    template <class T, typename = std::enable_if_t<!std::is_same_v<std::decay_t<T>, Any> &&
Неужели enable_if потребовался?

2024-02-05 15:08 UTC, DimaTrushin commented on Any.h
> +    const std::type_info &Type() const noexcept {
Вот это противоречит самой идее стирающего типа. Плюс это использует rtti. Это для дебага или где-то используется?

2024-02-05 15:08 UTC, DimaTrushin commented on Layer.h
> +    Layer();
Зачем тебе дефолтный конструктор для слоя?

2024-02-05 15:08 UTC, DimaTrushin commented on Layer.h
> +    Layer(Input input_size, Output output_size, const ActivationFunction &f);
Лучше ActivationFunction съедать by value тогда уж и потом мувать содержимое. Либо нужна еще одна версия, где ты принимаешь по lvalue ссылке.

2024-02-05 15:08 UTC, DimaTrushin commented on Layer.h
> +
Убрать лишние вертикальные пробелы.

2024-02-05 15:08 UTC, DimaTrushin commented on Layer.h
> +    Vector EvaluateDerivative(const Vector &x) const noexcept;
Можно кстати назвать evaluate0 и evaluate1. Это как идея по поводу сокращения названий.

2024-02-05 15:08 UTC, DimaTrushin commented on Layer.h
> +    explicit Input(size_t size);
Тут лучше сделать конструкторы inline, чтобы они полностью из кода оптимизировались, а не линковались.

2024-02-05 15:08 UTC, DimaTrushin commented on Layer.cpp
> +    return result;
Странно выглядит. Почему нельзя было сделать через unaryExpr? Тогда можно было не создавать временный вектор result в этом месте.

2024-02-05 15:08 UTC, DimaTrushin commented on Layer.cpp
> +    bias_ -= learning_rate() * bias_grad;
Ты тут испльзуешь разный learning_rate! Надо
```cpp
Scalar learningRate = learning_rate();
...
```
Это к вопросу почему опасно по ссылкам все передавать или делать неконстантные методы обращения к данным.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +    return norm_gen.generate<Matrix>(rows, columns, urng);
Если я правильно помню, то у EigenRand rows и columns типа int.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +    static Eigen::Rand::NormalGen<float> norm_gen{0, 1};
Почему float? А не Scalar? Тем более, что генератор у тебя 64 битный.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +std::vector<Vector> ReadLabels(const std::filesystem::path &path) {
Порядок методов в cpp файле должен быть точно такой же как в h файле!

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +    }
Выглядит как нарушение уровня абстракции. Вот это у тебя единственная содержательная функция. И я бы тут хотел видеть одну строчку
```cpp
return read_labels(...);
```

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +    }
Нарушение уровня абстракции. Тут ты просто проверяешь корректность вызовом некоторой функции.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +    }
Выглядит как нарушение уровня абстракции. По сути тебе нужен class ReadBFile который в своем конструкторе пытается открыть path на бинарное чтение и кидает в конструкторе исключение, если не получилось. И в своем интерфейсе пробрасывает метод read.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +namespace {
Я обычно анонимный namespace помещаю внутрь namespace проекта. Или того, где я работаю. Вот надо подумать есть ли в чем-то разница в этом случае.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +namespace nn {
вертикальный пробел между неймспейсами.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +
А вот этот убрать.

2024-02-05 15:08 UTC, DimaTrushin commented on utils.cpp
> +                    std::cout << '#';
5 вложенных scope. Даже в ядре Linux разрешено не более 3. Но думаю для дебажной функции можно оставить.

2024-04-04 19:45 UTC, boboxa2010 commented on Any.h
> +        return *this;
https://en.wikibooks.org/wiki/More_C++_Idioms/Copy-and-swap

Мне кажется, что так понятнее.

2024-04-04 19:51 UTC, boboxa2010 commented on Any.h
> +    const std::type_info &Type() const noexcept {
Да, для дебага, уже убрал

2024-04-04 19:52 UTC, boboxa2010 commented on Any.h
> +                                          std::is_copy_constructible_v<std::decay_t<T>>>>
мне казалось, что "Если есть шаблонный конструктор и не шаблонный, то нешаблонный всегда в приоритете" не работает, поэтому это все написал, уже исправил

2024-04-11 19:45 UTC, boboxa2010 commented on main.cpp
> +    nn::AsciiRender(train.X[0], train.y[0]);
Дебаг

2024-05-15 08:11 UTC, DimaTrushin requested changes
Очень хорошо. Сделал пару очень мелких замечаний и написал какие-то рассуждения по тому как я смотрю на написание кода в некоторых местах, они скорее информационные нежели требования к исправлению.

2024-05-15 08:11 UTC, DimaTrushin commented on Library/inc/ActivationFunctions.h
> +    Matrix EvaluateDerivative(const Matrix &v) const;
А почему этого метода нет в интерфейсе ActivationFunction?

2024-05-15 08:11 UTC, DimaTrushin commented on Library/inc/Any.h
> +
Не пиши в глобальное пространство имен, если тебе нужен библиотечный код, то можешь просто написать его в отдельном пространстве имен.

2024-05-15 08:11 UTC, DimaTrushin commented on Library/inc/BFile.h
> +        file_.open(file_name, std::ios::binary);
Это можно сделать в списке инициализации.

2024-05-15 08:11 UTC, DimaTrushin commented on Library/inc/BFile.h
> +        if (!file_.is_open()) {
Я в целом наоборот стараюсь делать обертки вокруг стандартных объектов, если они бросают исключения. Дело в том, что для файлового потока это нормально, если он не открылся в конструкторе. То есть у тебя может существовать корректно не открывшийся поток. Просто его надо уметь проверить открылся ли он и если нет, из него нельзя читать. Просто если у тебя какой-то кусок кода пытается открыть файловый поток и у него не получилось, то он же и принимает ршения, что делать. Ему не надо сообщать выше с помощью исключения, что файл не открылся. Так же ты не хочешь завалить программу во время исполнения и потерять все данные, только потому что кто-то неверно указал название файла. Это в целом плохая тема кидать исключения в такой ситуации. Исключения стоит кидать, если ты не смог получить доступ к жизненно важным ресурсам для работы приложения, будь то какие-то драйвера без которых приложение нельзя запустить или еще какие-то ресурсы операционной системы. Потому что в этом случае тебе действительно ничего не остается как умереть после исключения. А вот невозможность открыть файл -- это вполне штатная ситуация.

2024-05-15 08:11 UTC, DimaTrushin commented on Library/inc/BFile.h
> +        if (!file_.is_open()) {
В целом идея создать класс для открытия именно бинарного файла -- хорошая идея. Мне лишь не нравится бросание исключения.

2024-05-15 08:11 UTC, DimaTrushin commented on Tests/CMakeLists.txt
> +add_subdirectory(src)
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-05-15 08:11 UTC, DimaTrushin commented on Library/src/utils.cpp
> +                 std::mt19937(std::random_device()()));
Вот это плохо. НИКОДА НЕ инициализируйся от случайных данных. Это дает тебе не тестируемое окружение. Ты же выше создал статический енератор в функциях для генерации векторов и матриц. Сделай тут то же самое. Более того, такой подход НЕ гарантирует нужного распределения, если оно тебе понадобится.

2024-05-15 08:11 UTC, DimaTrushin commented on Library/src/Network.cpp
> +                             std::move(ActivationFunction(*it)));
Здесь std::move лишний потому что ты и так строишь с помощью конструктора ActivationFunction и потому у тебя и так rvalue тут стоит.
Еще замечание, std::initializer_list всегда содержит только константные объекты. Потому из него нельзя мувнуть данные. Это огромный недостаток, но так сделан язык. И это дает оромное неудобство по созданию конструкторов, которые бы могли принимать данные и воровать их внутренности.

2024-05-15 08:11 UTC, DimaTrushin commented on Library/src/MnistDataset.cpp
> +    file->read(reinterpret_cast<char *>(&magic_number), sizeof(magic_number));
Чтобы избежать кастов, можно создать отдельную функцию вроде ReadUint32.

2024-05-15 08:11 UTC, DimaTrushin commented on Library/inc/Network.h
> +
Я бы в хедерах вертикалные пробелы между функциями убрал. Оставил бы пробелы которые отделяют конструкторы от остального публичного интерфейса (если он большой его тоже можно поделить парой пробелов), еще в приватной части оставил пробел между методами и данными класса (если есть статические, то еще и между статическими данными и данными класса пробел). Это просто убирает лишнюю высоту класса и позволяет визуально сгруппировать важные сегменты кода.

Еще соит оставлять пробелы в хедере, если ты пишешь имплементации шаблонных методов, то их тоже стоит отделять пробелами.

2024-05-18 16:24 UTC, boboxa2010 commented on Library/inc/ActivationFunctions.h
> +    Matrix EvaluateDerivative(const Matrix &v) const;
он оказался ненужным

2024-05-19 18:59 UTC, DimaTrushin approved these changes

2024-05-20 07:44 UTC, merged